"""Periodic sampler smoke: spectrum along the example closed geodesic A.

Path-local only. Not the measure average.
"""
from __future__ import annotations

import json
from pathlib import Path

import numpy as np

import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))
from certificates.qr_error_model import LyapEstimate, report_side_by_side

ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "data" / "kz_along_A.json"


def main() -> None:
    rec = json.loads(DATA.read_text())
    # Exact orbit spectrum (normalized by log ρ(A))
    vals = tuple(rec["normalized_by_log_rho"])
    # Exact on this finite word → err ~ 0 for the normalized ratio claim
    err = tuple(0.0 for _ in vals)
    periodic = LyapEstimate(
        values=vals,
        err=err,
        steps=1,
        method="exact_orbit",
        notes="closed geodesic generated by A; path-local",
    )
    # Placeholder generic until Harper lands the long-path sampler
    generic = LyapEstimate(
        values=(0.43, 0.43, -0.43, -0.43),
        err=(0.05, 0.05, 0.05, 0.05),
        steps=0,
        method="qr_float",
        notes="PLACEHOLDER — isotropic random-walk contrast from prior note",
    )
    print(report_side_by_side(periodic, generic))
    print()
    print("periodic λ1+/λ2+ (normalized):", periodic.lambda1_plus, periodic.lambda2_plus)
    print("ratio:", periodic.ratio)
    print("scaled to sum 6/7:", rec["scaled_to_6_7"])
    print("promote_ready: false")


if __name__ == "__main__":
    main()
